CREATE TABLE food_type (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    unit VARCHAR(255) NOT NULL,
    calories_per_unit FLOAT NOT NULL,
    picture BLOB
);

CREATE TABLE food (
    id INT PRIMARY KEY AUTO_INCREMENT,
    type_id INT NOT NULL,
    household_id INT NOT NULL,
    expiration_date DATE NOT NULL,
    amount INT NOT NULL,
    FOREIGN KEY (type_id) REFERENCES food_type(id)
);

CREATE TABLE extra_resident_type (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  consumption_water FLOAT NOT NULL,
  consumption_food FLOAT NOT NULL
);

CREATE TABLE household (
  id INT AUTO_INCREMENT PRIMARY KEY,
  adress VARCHAR(255) NOT NULL,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL,
  amount_water FLOAT NOT NULL,
  last_water_change DATE NOT NULL
);

CREATE TABLE extra_resident (
  id INT AUTO_INCREMENT PRIMARY KEY,
  household_id INT NOT NULL,
  type_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  FOREIGN KEY (household_id) REFERENCES household(id),
  FOREIGN KEY (type_id) REFERENCES extra_resident_type(id)
);

CREATE TABLE `user` (
  id INT NOT NULL AUTO_INCREMENT,
  household_id INT DEFAULT NULL,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email_confirmed BOOLEAN DEFAULT FALSE,
  is_admin BOOLEAN DEFAULT FALSE,
  is_super_admin BOOLEAN DEFAULT FALSE,
  first_name VARCHAR(255) DEFAULT NULL,
  last_name VARCHAR(255) DEFAULT NULL,
  share_position_household BOOLEAN DEFAULT FALSE,
  share_position_group BOOLEAN DEFAULT FALSE,
  picture BLOB,
  PRIMARY KEY (id),
  UNIQUE (email),
  UNIQUE (username),
  FOREIGN KEY (household_id) REFERENCES household(id) ON DELETE SET NULL
);
CREATE TABLE map_object_type (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  icon VARCHAR(255) NOT NULL
);

CREATE TABLE map_object (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_id INT,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL,
  opening TIME,
  closing TIME,
  contact_phone VARCHAR(30),
  contact_email VARCHAR(100),
  contact_name VARCHAR(100),
  description TEXT,
  picture BLOB,
  FOREIGN KEY (type_id) REFERENCES map_object_type(id) ON DELETE CASCADE
);

