name: Build and Checkstyle

on:
  push:
    branches:
      - main
      - dev
      - 40-create-pipeline-in-github

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.5-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean install

  checkstyle:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.5-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html
